foil:
  xtalname: 'Ni.xtal'
  sig: 20.0
  omega: 0.0
  EkeV: 30
  Ehistmin: 15
  thickness: 100

EMTKD:
  thetac: 10.0
  xpc: 0
  ypc: 320
  omega: 0.0
  energymin: 22.0
  energymax: 30.0
  dwelltime: 100 

  